import type { Metadata } from "next";
import Providers from "./providers";
import Header from "@/components/theme/Header";
import {getUserFromCookie} from "@/backend/actions/user/getUser.action";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getUserFromCookie()

  return (
    <html
      lang="fa"
      dir="rtl"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Header user={user!} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
